/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './router/__root'
import { Route as RootRouteImport } from './router/rootRoute'
import { Route as PlannerRouteImport } from './router/plannerRoute'
import { Route as IndexRouteImport } from './router/indexRoute'

// Create/Update Routes

const RootRouteRoute = RootRouteImport.update({
  path: '/rootRoute',
  getParentRoute: () => rootRoute,
} as any)

const PlannerRouteRoute = PlannerRouteImport.update({
  path: '/plannerRoute',
  getParentRoute: () => rootRoute,
} as any)

const IndexRouteRoute = IndexRouteImport.update({
  path: '/indexRoute',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/indexRoute': {
      id: '/indexRoute'
      path: '/indexRoute'
      fullPath: '/indexRoute'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRoute
    }
    '/plannerRoute': {
      id: '/plannerRoute'
      path: '/plannerRoute'
      fullPath: '/plannerRoute'
      preLoaderRoute: typeof PlannerRouteImport
      parentRoute: typeof rootRoute
    }
    '/rootRoute': {
      id: '/rootRoute'
      path: '/rootRoute'
      fullPath: '/rootRoute'
      preLoaderRoute: typeof RootRouteImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRouteRoute,
  PlannerRouteRoute,
  RootRouteRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "children": [
        "/indexRoute",
        "/plannerRoute",
        "/rootRoute"
      ]
    },
    "/indexRoute": {
      "filePath": "indexRoute.tsx"
    },
    "/plannerRoute": {
      "filePath": "plannerRoute.tsx"
    },
    "/rootRoute": {
      "filePath": "rootRoute.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
